version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    docker:
      - image: cimg/node:18.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run serve

      - aws-s3/sync:
          from: dist
          to: 's3://rahulthakerportfolio/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
